var N=world.getBlockName(position);
var M=world.getBlockMetadata(position);
if(N=="jinshucraft:VariationSapling"&&M==0){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		mod.loadScript("WillowGrow.js");
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}
else if(N=="jinshucraft:VariationSapling"&&M==1){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		mod.loadScript("VariationWorking1.js");
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}
else if(N=="minecraft:sapling"&&M==0){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		mod.loadScript("OakGrow.js");
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}
else if(N=="jinshucraft:PineTree"&&M==0){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		mod.loadScript("PineGrow.js");
		if(world.getBlockName(position)=="jinshucraft:PineTree"&&world.getBlockMetadata(position)==0){
			world.setBlockAndMetadata(position,"jinshucraft:PineWood",0);
		}
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}
else if(N=="jinshucraft:CocoaTree"&&M==0){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		mod.loadScript("CocoaGrow.js");
		if(world.getBlockName(position)=="jinshucraft:CocoaTree"&&world.getBlockMetadata(position)==0){
			world.setBlockAndMetadata(position,"jinshucraft:CocoaWood",0);
		}
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}
else if(N=="BiomesOPlenty:colorizedSaplings"&&M==2){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		mod.loadScript("PalmGrow.js");
		if(world.getBlockName(position)=="BiomesOPlenty:colorizedSaplings"&&world.getBlockMetadata(position)==2){
			world.setBlockAndMetadata(position,"BiomesOPlenty:logs2",3);
		}
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}
else if(N=="BiomesOPlenty:colorizedSaplings"&&M==4){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		mod.loadScript("WillowGrow.js");
		if(world.getBlockName(position)=="BiomesOPlenty:colorizedSaplings"&&world.getBlockMetadata(position)==4){
			world.setBlockAndMetadata(position,"BiomesOPlenty:logs3",1);
		}
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}
else if(N=="minefantasy2:ironbark_sapling"&&M==0){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
}
else if(N=="jinshucraft:Shoot"&&M==0){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		world.setBlockAndMetadata(position,"minecraft:sapling",0);
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}
else if(N=="jinshucraft:Shoot"&&M==1){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		world.setBlockAndMetadata(position,"jinshucraft:PineTree",0);
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}
else if(N=="jinshucraft:Shoot"&&M==2){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		world.setBlockAndMetadata(position,"jinshucraft:CocoaTree",0);
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}
else if(N=="jinshucraft:Shoot"&&M==3){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		world.setBlockAndMetadata(position,"BiomesOPlenty:colorizedSaplings",2);
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}
else if(N=="jinshucraft:Shoot"&&M==4){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		world.setBlockAndMetadata(position,"BiomesOPlenty:colorizedSaplings",4);
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}
else if(N=="jinshucraft:Shoot"&&M==5){
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z++;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.x--;
	world.spawnParticle("happyVillager",position,0,3,0);
	position.z--;
	if(Math.random()<0.3){
		world.setBlockAndMetadata(position,"minefantasy2:ironbark_sapling",0);
	}
	player.removeFromSlot(player.getCurrentSlot(),1);
}