var aa;
var bb;
var cc;
var xxx=position.x;
var yyy=position.y;
var zzz=position.z;
position.y++;
for(aa=0;aa<9;aa++)
   {if (world.getBlockName(position)!="minecraft:air")
       {break;}
    position.y++;}
if (aa>=9)
   {position.y-=10;
    for(aa=0;aa<9;aa++)
	   {world.setBlock(position,"jinshucraft:CocoaWood");
        position.y++;}
	position.y-=2;
	position.x-=2;
	position.z-=2;
	for(aa=0;aa<5;aa++)
	   {for(bb=0;bb<5;bb++)
		   {if(world.getBlockName(position)=="minecraft:air")
		      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
		    position.x++;}
		position.x-=5;
		position.z++;}
	position.x++;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x++;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x++;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x+=2;
	position.z-=2;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.z--;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.z--;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x-=2;
	position.z-=2;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x--;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x--;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.z+=2;
	position.x-=2;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.z++;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.z++;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.y++;
	position.x++;
	position.z-=3;
    for(aa=0;aa<5;aa++)
	   {for(bb=0;bb<5;bb++)
		   {if(world.getBlockName(position)=="minecraft:air")
		      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
		    position.x++;}
		position.x-=5;
		position.z++;}
	position.x++;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x++;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x++;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x+=2;
	position.z-=2;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.z--;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.z--;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x-=2;
	position.z-=2;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x--;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x--;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.z+=2;
	position.x-=2;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.z++;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.z++;
    if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.y++;
	position.x+=2;
	for(aa=0;aa<3;aa++)
	   {for(bb=0;bb<3;bb++)
	       {if(world.getBlockName(position)=="minecraft:air")
              {world.setBlock(position,"jinshucraft:CocoaLeaves");};
		    position.x++;}
	    position.x-=3;
        position.z--;}
	position.y++;
	position.x++;
	position.z++;
	if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.z++;
	if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x--;
	if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x+=2;
	if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.x--;
	position.z++;
	if(world.getBlockName(position)=="minecraft:air")
      {world.setBlock(position,"jinshucraft:CocoaLeaves");}
    position.z--;
	position.y-=8;
    for(aa=0;aa<7;aa++)
	   {if(Math.random()<0.3)
		    {cc=Math.random();
		     if(cc<0.25){position.x--;if(world.getBlockName(position)=="minecraft:air"||world.getBlockName(position)=="jinshucraft:CocoaLeaves"){world.setBlockAndMetadata(position,"minecraft:cocoa",3);};position.x++;}
		     else if(cc<0.5 && cc>=0.25){position.x++;if(world.getBlockName(position)=="minecraft:air"||world.getBlockName(position)=="jinshucraft:CocoaLeaves"){world.setBlockAndMetadata(position,"minecraft:cocoa",1);};position.x--;}
		     else if(cc<0.75 && cc>=0.5){position.z--;if(world.getBlockName(position)=="minecraft:air"||world.getBlockName(position)=="jinshucraft:CocoaLeaves"){world.setBlockAndMetadata(position,"minecraft:cocoa",0);};position.z++;}
		     else if(cc<1 && cc>=0.75){position.z++;if(world.getBlockName(position)=="minecraft:air"||world.getBlockName(position)=="jinshucraft:CocoaLeaves"){world.setBlockAndMetadata(position,"minecraft:cocoa",2);};position.z--;};}
        position.y++;}}
position.x=xxx;
position.y=yyy;
position.z=zzz;