var s=0;
var x,y,z,i,j;
var xz=0;
var xf=0;
var zz=0;
var zf=0;
var aa,bb,cc,dd;
var ss=0;
var addd=0;
position.x++;
if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
  {for(i=0;i<17;i++)
	  {if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		 {position.x--;
	      position.y--;
	      if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		    {position.y++;
		     x=position.x;
			 y=position.y;
			 z=position.z;
			 s=1;}}
       position.x++;}}
else 
  {position.x--;
   position.z++;
   if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
     {for(i=0;i<17;i++)
	     {if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.z--;
		     position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;
		        x=position.x;
			    y=position.y;
			    z=position.z;
				s=1;}}
          position.z++;}}
   else
   {position.z-=2;
    if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
      {position.z++;
       position.x--;
       if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
	     {position.x++;
	      position.y--;
		  if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		    {position.y++;
             x=position.x;
			 y=position.y;
			 z=position.z;
             s=1;}}}}}
if(s==1)
  {position.x=x;
   position.y=y;
   position.z=z;
   position.x++;
   if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
     {xz=1;}
   position.x-=2;
   if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
     {xf=1;}
   position.x++;position.z++;
   if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
     {zz=1;}
   position.z-=2;
   if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
	 {zf=1;} 
   position.z++;
   if(xz==1&&xf==0&&zz==1&&zf==0)
     {for(aa=1;aa<19;aa++)
	     {position.x++;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.x--;
		     position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;break;}}}
	  for(bb=1;bb<19;bb++)
	     {position.z++;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.z--;
			 position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;break;}}}
	  for(cc=1;cc<19;cc++)
	     {position.x--;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.x++;
			 position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;break;}}}
	  for(dd=1;dd<19;dd++)
	     {position.z--;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.z++;
			 position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
	           {position.y++;ss=1;break;}}}}
   if(xz==1&&xf==0&&zz==0&&zf==1)
     {for(aa=1;aa<19;aa++)
	     {position.x++;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.x--;
		     position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;break;}}}
	  for(bb=1;bb<19;bb++)
	     {position.z--;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.z++;
			 position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;break;}}}
	  for(cc=1;cc<19;cc++)
	     {position.x--;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.x++;
			 position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;break;}}}
	  for(dd=1;dd<19;dd++)
	     {position.z++;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.z--;
			 position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
	           {position.y++;ss=1;break;}}}}
   if(xz==0&&xf==1&&zz==1&&zf==0)
     {for(aa=1;aa<19;aa++)
	     {position.x--;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.x++;
		     position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;break;}}}
	  for(bb=1;bb<19;bb++)
	     {position.z++;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.z--;
			 position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;break;}}}
	  for(cc=1;cc<19;cc++)
	     {position.x++;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.x--;
			 position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;break;}}}
	  for(dd=1;dd<19;dd++)
	     {position.z--;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.z++;
			 position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
	           {position.y++;ss=1;break;}}}}
   if(xz==0&&xf==1&&zz==0&&zf==1)
     {for(aa=1;aa<19;aa++)
	     {position.x--;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.x++;
		     position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;break;}}}
	  for(bb=1;bb<19;bb++)
	     {position.z--;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.z++;
			 position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;break;}}}
	  for(cc=1;cc<19;cc++)
	     {position.x++;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.x--;
			 position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
		       {position.y++;break;}}}
	  for(dd=1;dd<19;dd++)
	     {position.z++;
	      if(world.getBlockName(position)!="jinshucraft:WoodenSieveFrame")
		    {position.z--;
			 position.y--;
	         if(world.getBlockName(position)=="jinshucraft:WoodenSieveFrame")
	           {position.y++;ss=1;break;}}}}
   if(ss==1)
     {if(aa==cc&&bb==dd)
		{position.x=x;
	     position.y=y;
		 position.z=z;
		 if(xz==1&&xf==0&&zz==1&&zf==0)
		   {position.x++;
	        position.z++;
			for(i=0;i<aa-2;i++)
			   {for(j=0;j<bb-2;j++)
				   {if(world.getBlockName(position)=="minecraft:air")
					  {addd++;}
				    position.z++;}
				position.z-=bb-2;
		        position.x++;}}
		 if(xz==1&&xf==0&&zz==0&&zf==1)
		   {position.x++;
	        position.z--;
			for(i=0;i<aa-2;i++)
			   {for(j=0;j<bb-2;j++)
				   {if(world.getBlockName(position)=="minecraft:air")
					  {addd++;}
				    position.z--;}
				position.z+=bb-2;
		        position.x++;}}
		 if(xz==0&&xf==1&&zz==1&&zf==0)
		   {position.x--;
	        position.z++;
			for(i=0;i<aa-2;i++)
			   {for(j=0;j<bb-2;j++)
				   {if(world.getBlockName(position)=="minecraft:air")
					  {addd++;}
				    position.z++;}
				position.z-=bb-2;
		        position.x--;}}
		 if(xz==0&&xf==1&&zz==0&&zf==1)
		   {position.x--;
	        position.z--;
			for(i=0;i<aa-2;i++)
			   {for(j=0;j<bb-2;j++)
				   {if(world.getBlockName(position)=="minecraft:air")
					  {addd++;}
				    position.z--;}
				position.z+=bb-2;
		        position.x--;}}
		 if(addd>=((aa-2)*(bb-2))&&player.getItemCount("jinshucraft:itemNet",3)>=((aa-2)*(bb-2)))
		   {player.remove("jinshucraft:itemNet",(aa-2)*(bb-2),3);
			position.x=x;
	        position.y=y;
			position.z=z;
			if(xz==1&&xf==0&&zz==1&&zf==0)
			  {position.x++;
		       position.z++;
			   for(i=0;i<aa-2;i++)
			      {for(j=0;j<bb-2;j++)
					  {world.setBlock(position,"jinshucraft:WillowTwigSieveNet");
				       world.setTileEntityStringData(position,"Sparsity","80");
					   world.setTileEntityStringData(position,"Durability","800");
					   world.setTileEntityStringData(position,"Times","0");
				       position.z++;}
				   position.z-=bb-2;
				   position.x++;}}
			if(xz==1&&xf==0&&zz==0&&zf==1)
			  {position.x++;
		       position.z--;
			   for(i=0;i<aa-2;i++)
			      {for(j=0;j<bb-2;j++)
					  {world.setBlock(position,"jinshucraft:WillowTwigSieveNet");
				       world.setTileEntityStringData(position,"Sparsity","80");
					   world.setTileEntityStringData(position,"Durability","800");
					   world.setTileEntityStringData(position,"Times","0");
				       position.z--;}
				   position.z+=bb-2;
				   position.x++;}}
			if(xz==0&&xf==1&&zz==1&&zf==0)
			  {position.x--;
		       position.z++;
			   for(i=0;i<aa-2;i++)
			      {for(j=0;j<bb-2;j++)
					  {world.setBlock(position,"jinshucraft:WillowTwigSieveNet");
				       world.setTileEntityStringData(position,"Sparsity","80");
					   world.setTileEntityStringData(position,"Durability","800");
					   world.setTileEntityStringData(position,"Times","0");
				       position.z++;}
				   position.z-=bb-2;
				   position.x--;}}
			if(xz==0&&xf==1&&zz==0&&zf==1)
			  {position.x--;
		       position.z--;
			   for(i=0;i<aa-2;i++)
			      {for(j=0;j<bb-2;j++)
					  {world.setBlock(position,"jinshucraft:WillowTwigSieveNet");
				       world.setTileEntityStringData(position,"Sparsity","80");
					   world.setTileEntityStringData(position,"Durability","800");
					   world.setTileEntityStringData(position,"Times","0");
				       position.z--;}
				   position.z+=bb-2;
                   position.x--;}}}
		 else if(player.getItemCount("jinshucraft:itemNet",3)<((aa-2)*(bb-2)))
		        {player.sendMessage("\u6750\u6599\u4e0d\u591f\u0021\u8fd8\u9700\u8981"+((aa-2)*(bb-2)-player.getItemCount("jinshucraft:itemNet",3))+"\u5f20\u67f3\u6761\u7ef3\u7f51\u3002")}}}}
		   